services:
  nginx:
    image: nginx:alpine
    container_name: nginx-single
    restart: always
    ports:
        - "80:80"
    volumes:
        - /data/projects/github.com/sapaude/docker-infras/www/nginx/conf.d/:/etc/nginx/conf.d/