version: '3'
services:
  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: some-clickhouse-server
    ports:
      - "8123:8123"
      - "9003:9000"
      - "9004:9004"
    expose:
      - 9009
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
      - /data/docker_volumes/clickhouse-data:/var/lib/clickhouse
      - /data/src/ssb-dbgen:/data/src/ssb-dbgen
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
